version: "3.3"
services:
  db:
    volumes:
      - ./db-init:/db-init
  api:
    volumes:
      - ./packages/api:/app
      - /app/node_modules
  web:
    volumes:
      - ./packages/web:/app
      - /app/node_modules
